### ISSUE TITLE
image not found error -home page

### ISSUE THREAD

**Issue by irbasnet** [SproutTechAus/sprouttech-website#34]
image is not loaded in home page, in feature section.

**Comment by irbasnet** [comment]
@prakashkhadka  please fix this bbug ASAP

**Comment by prakashkhadka** [comment]
@gitrazesh Thanks for pointing out. I will fix it tonight.

**Comment by prakashkhadka** [comment]
@gitrazesh I fixed it. I found the picture to big and its format was wrong.
